-- Инициализация базы данных реабилитационного центра (PostgreSQL)

DROP TABLE IF EXISTS rehabilitation_plans, procedures, therapists, patients CASCADE;

CREATE TABLE IF NOT EXISTS patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL CHECK (char_length(trim(first_name)) > 0),
    last_name VARCHAR(50) NOT NULL CHECK (char_length(trim(last_name)) > 0),
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    birth_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED'))
);

CREATE TABLE IF NOT EXISTS therapists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL CHECK (char_length(trim(full_name)) > 0),
    specialization VARCHAR(40) NOT NULL
        CHECK (specialization IN ('PHYSIOTHERAPIST', 'MASSAGE_THERAPIST', 'SPEECH_THERAPIST',
                                  'OCCUPATIONAL_THERAPIST', 'PSYCHOLOGIST')),
    phone VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    hire_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS procedures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    therapist_id BIGINT NOT NULL REFERENCES therapists(id) ON DELETE RESTRICT,
    name VARCHAR(100) NOT NULL CHECK (char_length(trim(name)) > 0),
    description VARCHAR(500),
    procedure_date TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL
        CHECK (status IN ('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS rehabilitation_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    therapist_id BIGINT NOT NULL REFERENCES therapists(id) ON DELETE RESTRICT,
    title VARCHAR(150) NOT NULL CHECK (char_length(trim(title)) > 0),
    goal VARCHAR(500) NOT NULL CHECK (char_length(trim(goal)) > 0),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL
        CHECK (status IN ('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT rehabilitation_plan_dates CHECK (end_date >= start_date)
);

-- Тестовые данные: 5 пациентов, 5 специалистов, 8 процедур и 6 планов.
INSERT INTO patients (id, first_name, last_name, phone, email, birth_date, status) VALUES
    (1, 'Иван', 'Петров', '+79990000001', 'ivan.petrov@example.com', '1988-04-12', 'ACTIVE'),
    (2, 'Мария', 'Соколова', '+79990000002', 'maria.sokolova@example.com', '1992-09-21', 'ACTIVE'),
    (3, 'Алексей', 'Орлов', '+79990000003', 'alexey.orlov@example.com', '1975-01-30', 'INACTIVE'),
    (4, 'Елена', 'Кузнецова', '+79990000004', 'elena.kuznetsova@example.com', '2001-06-05', 'ACTIVE'),
    (5, 'Сергей', 'Морозов', '+79990000005', 'sergey.morozov@example.com', '1968-11-17', 'ARCHIVED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO therapists (id, full_name, specialization, phone, email, hire_date) VALUES
    (1, 'Анна Васильева', 'PHYSIOTHERAPIST', '+79991110001', 'anna.vasilieva@example.com', '2018-02-12'),
    (2, 'Олег Смирнов', 'MASSAGE_THERAPIST', '+79991110002', 'oleg.smirnov@example.com', '2019-05-20'),
    (3, 'Наталья Волкова', 'SPEECH_THERAPIST', '+79991110003', 'natalia.volkova@example.com', '2020-09-01'),
    (4, 'Дмитрий Федоров', 'OCCUPATIONAL_THERAPIST', '+79991110004', 'dmitry.fedorov@example.com', '2017-11-15'),
    (5, 'Ирина Павлова', 'PSYCHOLOGIST', '+79991110005', 'irina.pavlova@example.com', '2021-03-10')
ON CONFLICT (id) DO NOTHING;

INSERT INTO procedures (id, patient_id, therapist_id, name, description, procedure_date, status) VALUES
    (1, 1, 1, 'Лечебная гимнастика', 'Комплекс упражнений для восстановления подвижности', '2026-09-01 10:00:00', 'COMPLETED'),
    (2, 1, 2, 'Массаж спины', 'Курс расслабляющего массажа', '2026-09-05 12:00:00', 'COMPLETED'),
    (3, 2, 1, 'Физиотерапия', 'Электрофорез и упражнения', '2026-10-07 09:30:00', 'PLANNED'),
    (4, 2, 3, 'Логопедическое занятие', 'Коррекция речи после травмы', '2026-10-08 14:00:00', 'IN_PROGRESS'),
    (5, 3, 4, 'Эрготерапия', 'Тренировка бытовых навыков', '2026-08-20 11:00:00', 'CANCELLED'),
    (6, 4, 1, 'Разработка сустава', 'Индивидуальная работа с суставом', '2026-10-10 10:30:00', 'PLANNED'),
    (7, 4, 5, 'Психологическая консультация', 'Поддержка во время восстановления', '2026-09-25 16:00:00', 'COMPLETED'),
    (8, 5, 2, 'Массаж конечностей', 'Поддерживающий массаж', '2026-07-18 13:00:00', 'CANCELLED')
ON CONFLICT (id) DO NOTHING;

INSERT INTO rehabilitation_plans (id, patient_id, therapist_id, title, goal, start_date, end_date, status) VALUES
    (1, 1, 1, 'Восстановление после перелома', 'Вернуть полный объем движений руки', '2026-08-20', '2026-10-20', 'ACTIVE'),
    (2, 2, 1, 'Укрепление мышц', 'Увеличить силу и выносливость', '2026-09-01', '2026-12-01', 'ACTIVE'),
    (3, 3, 4, 'Самостоятельность в быту', 'Восстановить навыки самообслуживания', '2026-05-01', '2026-08-01', 'COMPLETED'),
    (4, 4, 3, 'Коррекция речи', 'Улучшить четкость произношения', '2026-09-15', '2026-11-15', 'DRAFT'),
    (5, 5, 2, 'Поддерживающий курс', 'Снизить мышечное напряжение', '2026-04-01', '2026-06-01', 'CANCELLED'),
    (6, 1, 5, 'Психологическая поддержка', 'Сформировать устойчивую мотивацию к лечению', '2026-09-10', '2026-12-10', 'ACTIVE')
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('patients', 'id'), COALESCE((SELECT MAX(id) FROM patients), 1));
SELECT setval(pg_get_serial_sequence('therapists', 'id'), COALESCE((SELECT MAX(id) FROM therapists), 1));
SELECT setval(pg_get_serial_sequence('procedures', 'id'), COALESCE((SELECT MAX(id) FROM procedures), 1));
SELECT setval(pg_get_serial_sequence('rehabilitation_plans', 'id'), COALESCE((SELECT MAX(id) FROM rehabilitation_plans), 1));
